# repost lib scons build script!

# Setup build env
env = Environment()
env.Append(CPPPATH = ['#include/','.','#base/public/'])
env.Append(CPPPATH = ['/usr/include/glib-2.0/','/usr/lib/glib-2.0/include/'])
debug = ARGUMENTS.get('debug', 0)
if int(debug):
   env.Append(CCFLAGS = '-g')

env.Append(CCFLAGS = '-DXP_UNIX=1')
Export('env')

# Packages
packages = '''
'''

env.ParseConfig( 'pkg-config --cflags --libs glib-2.0')
# Sub dir scripts

# Targets
env.SharedLibrary('npapi-rpl',Glob('*.cpp'))

